// Static Mock Data for School Management System

export const teachers = [
  {
    id: 1,
    name: "Dr. Sarah Johnson",
    email: "sarah.j@school.com",
    phone: "555-0101",
    subjects: [1],
    qualification: "Ph.D. in Mathematics",
    experience: 15,
    employmentType: "Full-time",
    joinDate: "2009-06-15",
  },
  {
    id: 2,
    name: "Mr. James Wilson",
    email: "james.w@school.com",
    phone: "555-0102",
    subjects: [2],
    qualification: "M.Sc. in Physics",
    experience: 12,
    employmentType: "Full-time",
    joinDate: "2012-08-01",
  },
  {
    id: 3,
    name: "Ms. Emily Brown",
    email: "emily.b@school.com",
    phone: "555-0103",
    subjects: [5],
    qualification: "M.A. in English",
    experience: 10,
    employmentType: "Full-time",
    joinDate: "2014-07-20",
  },
  {
    id: 4,
    name: "Mr. Michael Chen",
    email: "michael.c@school.com",
    phone: "555-0104",
    subjects: [3],
    qualification: "Ph.D. in Chemistry",
    experience: 8,
    employmentType: "Full-time",
    joinDate: "2016-09-10",
  },
  {
    id: 5,
    name: "Ms. Lisa Anderson",
    email: "lisa.a@school.com",
    phone: "555-0105",
    subjects: [4],
    qualification: "M.Sc. in Biology",
    experience: 11,
    employmentType: "Full-time",
    joinDate: "2013-06-05",
  },
  {
    id: 6,
    name: "Mr. Robert Taylor",
    email: "robert.t@school.com",
    phone: "555-0106",
    subjects: [6],
    qualification: "M.A. in History",
    experience: 14,
    employmentType: "Full-time",
    joinDate: "2010-08-15",
  },
  {
    id: 7,
    name: "Ms. Jennifer Martinez",
    email: "jennifer.m@school.com",
    phone: "555-0107",
    subjects: [7],
    qualification: "M.Sc. in Geography",
    experience: 9,
    employmentType: "Full-time",
    joinDate: "2015-07-01",
  },
  {
    id: 8,
    name: "Mr. David Lee",
    email: "david.l@school.com",
    phone: "555-0108",
    subjects: [8],
    qualification: "M.Tech in CS",
    experience: 7,
    employmentType: "Full-time",
    joinDate: "2017-08-20",
  },
  {
    id: 9,
    name: "Ms. Amanda White",
    email: "amanda.w@school.com",
    phone: "555-0109",
    subjects: [9],
    qualification: "MFA in Fine Arts",
    experience: 6,
    employmentType: "Part-time",
    joinDate: "2018-09-01",
  },
  {
    id: 10,
    name: "Mr. Christopher Davis",
    email: "chris.d@school.com",
    phone: "555-0110",
    subjects: [10],
    qualification: "B.P.Ed",
    experience: 13,
    employmentType: "Full-time",
    joinDate: "2011-06-10",
  },
  {
    id: 11,
    name: "Ms. Rachel Green",
    email: "rachel.g@school.com",
    phone: "555-0111",
    subjects: [11],
    qualification: "M.A. in Music",
    experience: 8,
    employmentType: "Part-time",
    joinDate: "2016-07-15",
  },
  {
    id: 12,
    name: "Mr. Daniel Kim",
    email: "daniel.k@school.com",
    phone: "555-0112",
    subjects: [12],
    qualification: "M.A. in Economics",
    experience: 10,
    employmentType: "Full-time",
    joinDate: "2014-08-01",
  },
  {
    id: 13,
    name: "Ms. Sophia Patel",
    email: "sophia.p@school.com",
    phone: "555-0113",
    subjects: [13],
    qualification: "M.A. in Hindi",
    experience: 12,
    employmentType: "Full-time",
    joinDate: "2012-09-01",
  },
  {
    id: 14,
    name: "Mr. Kevin O'Brien",
    email: "kevin.o@school.com",
    phone: "555-0114",
    subjects: [14],
    qualification: "M.A. in French",
    experience: 9,
    employmentType: "Part-time",
    joinDate: "2015-06-20",
  },
  {
    id: 15,
    name: "Ms. Olivia Thompson",
    email: "olivia.t@school.com",
    phone: "555-0115",
    subjects: [15],
    qualification: "M.A. in Psychology",
    experience: 7,
    employmentType: "Full-time",
    joinDate: "2017-08-10",
  },
  {
    id: 16,
    name: "Mr. Benjamin Clark",
    email: "ben.c@school.com",
    phone: "555-0116",
    subjects: [16],
    qualification: "M.A. in Political Science",
    experience: 11,
    employmentType: "Full-time",
    joinDate: "2013-07-01",
  },
  {
    id: 17,
    name: "Ms. Natalie Wright",
    email: "natalie.w@school.com",
    phone: "555-0117",
    subjects: [17],
    qualification: "M.A. in Sociology",
    experience: 8,
    employmentType: "Full-time",
    joinDate: "2016-09-15",
  },
  {
    id: 18,
    name: "Mr. Marcus Johnson",
    email: "marcus.j@school.com",
    phone: "555-0118",
    subjects: [18],
    qualification: "MBA",
    experience: 10,
    employmentType: "Full-time",
    joinDate: "2014-08-20",
  },
  {
    id: 19,
    name: "Ms. Grace Liu",
    email: "grace.l@school.com",
    phone: "555-0119",
    subjects: [19],
    qualification: "M.A. in Chinese",
    experience: 6,
    employmentType: "Part-time",
    joinDate: "2018-07-01",
  },
  {
    id: 20,
    name: "Mr. Samuel Jackson",
    email: "sam.j@school.com",
    phone: "555-0120",
    subjects: [20],
    qualification: "MFA in Theatre",
    experience: 9,
    employmentType: "Part-time",
    joinDate: "2015-08-15",
  },
];

export const subjects = [
  {
    id: 1,
    name: "Mathematics",
    code: "MATH",
    teacherId: 1,
    description: "Algebra, Geometry, Calculus, Statistics",
    credits: 5,
  },
  {
    id: 2,
    name: "Physics",
    code: "PHY",
    teacherId: 2,
    description: "Mechanics, Thermodynamics, Electromagnetism",
    credits: 4,
  },
  {
    id: 3,
    name: "Chemistry",
    code: "CHEM",
    teacherId: 4,
    description: "Organic, Inorganic, Physical Chemistry",
    credits: 4,
  },
  {
    id: 4,
    name: "Biology",
    code: "BIO",
    teacherId: 5,
    description: "Zoology, Botany, Human Anatomy",
    credits: 4,
  },
  {
    id: 5,
    name: "English Literature",
    code: "ENG",
    teacherId: 3,
    description: "Prose, Poetry, Drama, Grammar",
    credits: 4,
  },
  {
    id: 6,
    name: "History",
    code: "HIST",
    teacherId: 6,
    description: "World History, Indian History, Modern History",
    credits: 3,
  },
  {
    id: 7,
    name: "Geography",
    code: "GEO",
    teacherId: 7,
    description: "Physical Geography, Human Geography",
    credits: 3,
  },
  {
    id: 8,
    name: "Computer Science",
    code: "CS",
    teacherId: 8,
    description: "Programming, Data Structures, Algorithms",
    credits: 4,
  },
  {
    id: 9,
    name: "Art",
    code: "ART",
    teacherId: 9,
    description: "Drawing, Painting, Sculpture",
    credits: 2,
  },
  {
    id: 10,
    name: "Physical Education",
    code: "PE",
    teacherId: 10,
    description: "Sports, Fitness, Health Education",
    credits: 2,
  },
  {
    id: 11,
    name: "Music",
    code: "MUS",
    teacherId: 11,
    description: "Vocal, Instrumental, Theory",
    credits: 2,
  },
  {
    id: 12,
    name: "Economics",
    code: "ECO",
    teacherId: 12,
    description: "Microeconomics, Macroeconomics",
    credits: 3,
  },
  {
    id: 13,
    name: "Hindi",
    code: "HIN",
    teacherId: 13,
    description: "Literature, Grammar, Composition",
    credits: 3,
  },
  {
    id: 14,
    name: "French",
    code: "FRE",
    teacherId: 14,
    description: "Language, Culture, Literature",
    credits: 3,
  },
  {
    id: 15,
    name: "Psychology",
    code: "PSY",
    teacherId: 15,
    description: "Cognitive, Developmental, Social Psychology",
    credits: 3,
  },
  {
    id: 16,
    name: "Political Science",
    code: "POL",
    teacherId: 16,
    description: "Political Theory, International Relations",
    credits: 3,
  },
  {
    id: 17,
    name: "Sociology",
    code: "SOC",
    teacherId: 17,
    description: "Social Structures, Institutions, Change",
    credits: 3,
  },
  {
    id: 18,
    name: "Business Studies",
    code: "BUS",
    teacherId: 18,
    description: "Management, Marketing, Finance",
    credits: 3,
  },
  {
    id: 19,
    name: "Mandarin",
    code: "MAN",
    teacherId: 19,
    description: "Language, Culture, Business Chinese",
    credits: 3,
  },
  {
    id: 20,
    name: "Drama",
    code: "DRA",
    teacherId: 20,
    description: "Acting, Directing, Production",
    credits: 2,
  },
];

export const classes = [
  {
    id: 1,
    grade: "Grade 1",
    section: "A",
    classTeacherId: 1,
    room: "101",
    capacity: 30,
    students: 28,
  },
  {
    id: 2,
    grade: "Grade 1",
    section: "B",
    classTeacherId: 2,
    room: "102",
    capacity: 30,
    students: 26,
  },
  {
    id: 3,
    grade: "Grade 2",
    section: "A",
    classTeacherId: 3,
    room: "103",
    capacity: 30,
    students: 29,
  },
  {
    id: 4,
    grade: "Grade 2",
    section: "B",
    classTeacherId: 4,
    room: "104",
    capacity: 30,
    students: 27,
  },
  {
    id: 5,
    grade: "Grade 3",
    section: "A",
    classTeacherId: 5,
    room: "201",
    capacity: 35,
    students: 32,
  },
  {
    id: 6,
    grade: "Grade 3",
    section: "B",
    classTeacherId: 6,
    room: "202",
    capacity: 35,
    students: 30,
  },
  {
    id: 7,
    grade: "Grade 4",
    section: "A",
    classTeacherId: 7,
    room: "203",
    capacity: 35,
    students: 33,
  },
  {
    id: 8,
    grade: "Grade 4",
    section: "B",
    classTeacherId: 8,
    room: "204",
    capacity: 35,
    students: 31,
  },
  {
    id: 9,
    grade: "Grade 5",
    section: "A",
    classTeacherId: 9,
    room: "301",
    capacity: 35,
    students: 34,
  },
  {
    id: 10,
    grade: "Grade 5",
    section: "B",
    classTeacherId: 10,
    room: "302",
    capacity: 35,
    students: 32,
  },
  {
    id: 11,
    grade: "Grade 6",
    section: "A",
    classTeacherId: 11,
    room: "303",
    capacity: 40,
    students: 38,
  },
  {
    id: 12,
    grade: "Grade 6",
    section: "B",
    classTeacherId: 12,
    room: "304",
    capacity: 40,
    students: 36,
  },
  {
    id: 13,
    grade: "Grade 7",
    section: "A",
    classTeacherId: 13,
    room: "401",
    capacity: 40,
    students: 39,
  },
  {
    id: 14,
    grade: "Grade 7",
    section: "B",
    classTeacherId: 14,
    room: "402",
    capacity: 40,
    students: 37,
  },
  {
    id: 15,
    grade: "Grade 8",
    section: "A",
    classTeacherId: 15,
    room: "403",
    capacity: 40,
    students: 38,
  },
  {
    id: 16,
    grade: "Grade 8",
    section: "B",
    classTeacherId: 16,
    room: "404",
    capacity: 40,
    students: 35,
  },
  {
    id: 17,
    grade: "Grade 9",
    section: "A",
    classTeacherId: 17,
    room: "501",
    capacity: 45,
    students: 42,
  },
  {
    id: 18,
    grade: "Grade 9",
    section: "B",
    classTeacherId: 18,
    room: "502",
    capacity: 45,
    students: 40,
  },
  {
    id: 19,
    grade: "Grade 10",
    section: "A",
    classTeacherId: 19,
    room: "503",
    capacity: 45,
    students: 43,
  },
  {
    id: 20,
    grade: "Grade 10",
    section: "B",
    classTeacherId: 20,
    room: "504",
    capacity: 45,
    students: 41,
  },
  {
    id: 21,
    grade: "Grade 11",
    section: "Science",
    classTeacherId: 1,
    room: "601",
    capacity: 50,
    students: 48,
  },
  {
    id: 22,
    grade: "Grade 11",
    section: "Commerce",
    classTeacherId: 12,
    room: "602",
    capacity: 50,
    students: 46,
  },
  {
    id: 23,
    grade: "Grade 11",
    section: "Arts",
    classTeacherId: 3,
    room: "603",
    capacity: 50,
    students: 44,
  },
  {
    id: 24,
    grade: "Grade 12",
    section: "Science",
    classTeacherId: 2,
    room: "604",
    capacity: 50,
    students: 47,
  },
  {
    id: 25,
    grade: "Grade 12",
    section: "Commerce",
    classTeacherId: 18,
    room: "605",
    capacity: 50,
    students: 45,
  },
  {
    id: 26,
    grade: "Grade 12",
    section: "Arts",
    classTeacherId: 6,
    room: "606",
    capacity: 50,
    students: 43,
  },
];

export const attendanceData = [
  { id: 1, studentId: 1, date: "2024-01-15", status: "present", classId: 21 },
  { id: 2, studentId: 2, date: "2024-01-15", status: "present", classId: 21 },
  { id: 3, studentId: 3, date: "2024-01-15", status: "absent", classId: 21 },
  { id: 4, studentId: 4, date: "2024-01-15", status: "present", classId: 21 },
  { id: 5, studentId: 5, date: "2024-01-15", status: "present", classId: 21 },
  { id: 6, studentId: 1, date: "2024-01-16", status: "present", classId: 21 },
  { id: 7, studentId: 2, date: "2024-01-16", status: "absent", classId: 21 },
  { id: 8, studentId: 3, date: "2024-01-16", status: "present", classId: 21 },
  { id: 9, studentId: 4, date: "2024-01-16", status: "present", classId: 21 },
  { id: 10, studentId: 5, date: "2024-01-16", status: "present", classId: 21 },
  { id: 11, studentId: 6, date: "2024-01-15", status: "present", classId: 22 },
  { id: 12, studentId: 7, date: "2024-01-15", status: "present", classId: 22 },
  { id: 13, studentId: 8, date: "2024-01-15", status: "late", classId: 22 },
  { id: 14, studentId: 9, date: "2024-01-15", status: "present", classId: 22 },
  { id: 15, studentId: 10, date: "2024-01-15", status: "present", classId: 22 },
];

export const gradesData = [
  {
    id: 1,
    studentId: 1,
    subjectId: 1,
    examType: "Midterm",
    marks: 85,
    maxMarks: 100,
    grade: "A",
    semester: "Fall 2024",
  },
  {
    id: 2,
    studentId: 1,
    subjectId: 2,
    examType: "Midterm",
    marks: 78,
    maxMarks: 100,
    grade: "B+",
    semester: "Fall 2024",
  },
  {
    id: 3,
    studentId: 1,
    subjectId: 3,
    examType: "Midterm",
    marks: 92,
    maxMarks: 100,
    grade: "A+",
    semester: "Fall 2024",
  },
  {
    id: 4,
    studentId: 1,
    subjectId: 4,
    examType: "Midterm",
    marks: 88,
    maxMarks: 100,
    grade: "A",
    semester: "Fall 2024",
  },
  {
    id: 5,
    studentId: 1,
    subjectId: 5,
    examType: "Midterm",
    marks: 90,
    maxMarks: 100,
    grade: "A+",
    semester: "Fall 2024",
  },
  {
    id: 6,
    studentId: 2,
    subjectId: 1,
    examType: "Midterm",
    marks: 72,
    maxMarks: 100,
    grade: "B",
    semester: "Fall 2024",
  },
  {
    id: 7,
    studentId: 2,
    subjectId: 2,
    examType: "Midterm",
    marks: 68,
    maxMarks: 100,
    grade: "C+",
    semester: "Fall 2024",
  },
  {
    id: 8,
    studentId: 2,
    subjectId: 3,
    examType: "Midterm",
    marks: 75,
    maxMarks: 100,
    grade: "B",
    semester: "Fall 2024",
  },
  {
    id: 9,
    studentId: 2,
    subjectId: 4,
    examType: "Midterm",
    marks: 80,
    maxMarks: 100,
    grade: "B+",
    semester: "Fall 2024",
  },
  {
    id: 10,
    studentId: 2,
    subjectId: 5,
    examType: "Midterm",
    marks: 82,
    maxMarks: 100,
    grade: "B+",
    semester: "Fall 2024",
  },
  {
    id: 11,
    studentId: 3,
    subjectId: 1,
    examType: "Midterm",
    marks: 95,
    maxMarks: 100,
    grade: "A+",
    semester: "Fall 2024",
  },
  {
    id: 12,
    studentId: 3,
    subjectId: 2,
    examType: "Midterm",
    marks: 88,
    maxMarks: 100,
    grade: "A",
    semester: "Fall 2024",
  },
  {
    id: 13,
    studentId: 3,
    subjectId: 3,
    examType: "Midterm",
    marks: 91,
    maxMarks: 100,
    grade: "A+",
    semester: "Fall 2024",
  },
  {
    id: 14,
    studentId: 3,
    subjectId: 4,
    examType: "Midterm",
    marks: 87,
    maxMarks: 100,
    grade: "A",
    semester: "Fall 2024",
  },
  {
    id: 15,
    studentId: 3,
    subjectId: 5,
    examType: "Midterm",
    marks: 93,
    maxMarks: 100,
    grade: "A+",
    semester: "Fall 2024",
  },
];

export const feeStructure = [
  {
    id: 1,
    grade: "Grade 1-5",
    tuitionFee: 15000,
    libraryFee: 2000,
    labFee: 1000,
    sportsFee: 1500,
    totalFee: 19500,
  },
  {
    id: 2,
    grade: "Grade 6-8",
    tuitionFee: 18000,
    libraryFee: 2500,
    labFee: 2000,
    sportsFee: 2000,
    totalFee: 24500,
  },
  {
    id: 3,
    grade: "Grade 9-10",
    tuitionFee: 22000,
    libraryFee: 3000,
    labFee: 3000,
    sportsFee: 2500,
    totalFee: 30500,
  },
  {
    id: 4,
    grade: "Grade 11-12",
    tuitionFee: 25000,
    libraryFee: 3500,
    labFee: 4000,
    sportsFee: 3000,
    totalFee: 35500,
  },
];

export const paymentsData = [
  {
    id: 1,
    studentId: 1,
    amount: 19500,
    date: "2024-01-05",
    type: "Tuition",
    status: "paid",
    method: "Online",
  },
  {
    id: 2,
    studentId: 2,
    amount: 19500,
    date: "2024-01-08",
    type: "Tuition",
    status: "paid",
    method: "Cash",
  },
  {
    id: 3,
    studentId: 3,
    amount: 19500,
    date: "2024-01-10",
    type: "Tuition",
    status: "paid",
    method: "Online",
  },
  {
    id: 4,
    studentId: 4,
    amount: 19500,
    date: "2024-01-12",
    type: "Tuition",
    status: "pending",
    method: null,
  },
  {
    id: 5,
    studentId: 5,
    amount: 19500,
    date: "2024-01-15",
    type: "Tuition",
    status: "paid",
    method: "Card",
  },
  {
    id: 6,
    studentId: 6,
    amount: 24500,
    date: "2024-01-06",
    type: "Tuition",
    status: "paid",
    method: "Online",
  },
  {
    id: 7,
    studentId: 7,
    amount: 24500,
    date: "2024-01-09",
    type: "Tuition",
    status: "paid",
    method: "Cash",
  },
  {
    id: 8,
    studentId: 8,
    amount: 24500,
    date: "2024-01-11",
    type: "Tuition",
    status: "pending",
    method: null,
  },
  {
    id: 9,
    studentId: 9,
    amount: 24500,
    date: "2024-01-14",
    type: "Tuition",
    status: "paid",
    method: "Online",
  },
  {
    id: 10,
    studentId: 10,
    amount: 24500,
    date: "2024-01-16",
    type: "Tuition",
    status: "paid",
    method: "Card",
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Annual Sports Day",
    date: "2025-02-15",
    type: "Sports",
    description:
      "Inter-house sports competition with track events, team sports, and athletic competitions. All students from Grade 5-12 are encouraged to participate.",
    location: "School Ground",
    time: "09:00 AM - 04:00 PM",
  },
  {
    id: 2,
    title: "Science Exhibition",
    date: "2025-02-28",
    type: "Academic",
    description:
      "Student science projects display showcasing innovative experiments and research work from all science departments.",
    location: "Science Block",
    time: "10:00 AM - 03:00 PM",
  },
  {
    id: 13,
    title: "Winter Break Begins",
    date: "2024-12-23",
    type: "Holiday",
    description:
      "Winter vacation starts for all students. Classes resume on January 6, 2025.",
    location: "-",
    time: "All Day",
  },
  {
    id: 14,
    title: "New Year Celebration",
    date: "2024-12-31",
    type: "Cultural",
    description:
      "School New Year party with cultural performances, music, and refreshments for students and staff.",
    location: "School Auditorium",
    time: "06:00 PM - 09:00 PM",
  },
  {
    id: 15,
    title: "Parent-Teacher Conference",
    date: "2025-01-15",
    type: "Meeting",
    description:
      "Individual meetings between parents and teachers to discuss student progress and academic performance for the first semester.",
    location: "Main Hall",
    time: "02:00 PM - 06:00 PM",
  },
  {
    id: 16,
    title: "Republic Day Celebration",
    date: "2025-01-26",
    type: "Cultural",
    description:
      "Flag hoisting ceremony, cultural programs, and patriotic songs to celebrate Republic Day.",
    location: "School Ground",
    time: "08:00 AM - 11:00 AM",
  },
  {
    id: 17,
    title: "Career Guidance Workshop",
    date: "2025-02-05",
    type: "Academic",
    description:
      "Expert counselors from leading universities will guide Grade 10-12 students on career options and college admissions.",
    location: "Seminar Hall",
    time: "10:00 AM - 02:00 PM",
  },
  {
    id: 18,
    title: "Inter-School Debate Competition",
    date: "2025-02-20",
    type: "Academic",
    description:
      "Annual debate competition with participation from 10 schools. Topics on current affairs and social issues.",
    location: "Auditorium",
    time: "09:30 AM - 04:00 PM",
  },
  {
    id: 19,
    title: "Health Check-up Camp",
    date: "2025-03-05",
    type: "Meeting",
    description:
      "Annual health screening for all students including dental, vision, and general health check-ups by certified medical professionals.",
    location: "Medical Room & Hall B",
    time: "09:00 AM - 03:00 PM",
  },
  {
    id: 20,
    title: "Art & Craft Exhibition",
    date: "2025-03-15",
    type: "Cultural",
    description:
      "Display of student artwork, paintings, sculptures, and craft projects from all grades. Parents are welcome to attend.",
    location: "Art Gallery",
    time: "10:00 AM - 05:00 PM",
  },
  {
    id: 3,
    title: "Parent-Teacher Meeting",
    date: "2025-03-10",
    type: "Meeting",
    description: "Discussion on student progress",
    location: "Main Hall",
    time: "02:00 PM - 05:00 PM",
  },
  {
    id: 4,
    title: "Annual Day Celebration",
    date: "2025-03-25",
    type: "Cultural",
    description: "Cultural performances and awards",
    location: "Auditorium",
    time: "05:00 PM - 09:00 PM",
  },
  {
    id: 5,
    title: "Midterm Examinations",
    date: "2025-04-01",
    type: "Academic",
    description: "First semester examinations",
    location: "All Classrooms",
    time: "09:00 AM - 12:00 PM",
  },
  {
    id: 6,
    title: "Summer Vacation",
    date: "2025-05-15",
    type: "Holiday",
    description: "Summer break begins",
    location: "-",
    time: "All Day",
  },
  {
    id: 7,
    title: "Teachers Day",
    date: "2025-09-05",
    type: "Cultural",
    description: "Celebration honoring teachers",
    location: "School Campus",
    time: "10:00 AM - 02:00 PM",
  },
  {
    id: 8,
    title: "Independence Day",
    date: "2025-08-15",
    type: "Holiday",
    description: "National holiday",
    location: "-",
    time: "All Day",
  },
  {
    id: 9,
    title: "Gandhi Jayanti",
    date: "2025-10-02",
    type: "Holiday",
    description: "National holiday",
    location: "-",
    time: "All Day",
  },
  {
    id: 10,
    title: "Diwali Break",
    date: "2025-11-01",
    type: "Holiday",
    description: "Festival holidays",
    location: "-",
    time: "All Day",
  },
  {
    id: 11,
    title: "Winter Carnival",
    date: "2025-12-20",
    type: "Cultural",
    description: "Annual winter festival",
    location: "School Ground",
    time: "11:00 AM - 06:00 PM",
  },
  {
    id: 12,
    title: "Christmas Holiday",
    date: "2025-12-25",
    type: "Holiday",
    description: "Christmas celebration",
    location: "-",
    time: "All Day",
  },
];

export const parentsData = [
  {
    id: 1,
    name: "Mr. Robert Smith",
    email: "robert.smith@email.com",
    phone: "555-1001",
    occupation: "Engineer",
    address: "123 Main St, City",
  },
  {
    id: 2,
    name: "Mrs. Sarah Smith",
    email: "sarah.smith@email.com",
    phone: "555-1002",
    occupation: "Doctor",
    address: "123 Main St, City",
  },
  {
    id: 3,
    name: "Mr. John Doe",
    email: "john.doe@email.com",
    phone: "555-1003",
    occupation: "Businessman",
    address: "456 Oak Ave, City",
  },
  {
    id: 4,
    name: "Mrs. Jane Doe",
    email: "jane.doe@email.com",
    phone: "555-1004",
    occupation: "Teacher",
    address: "456 Oak Ave, City",
  },
  {
    id: 5,
    name: "Mr. Michael Johnson",
    email: "michael.j@email.com",
    phone: "555-1005",
    occupation: "Lawyer",
    address: "789 Pine Rd, City",
  },
  {
    id: 6,
    name: "Mrs. Lisa Johnson",
    email: "lisa.j@email.com",
    phone: "555-1006",
    occupation: "Architect",
    address: "789 Pine Rd, City",
  },
  {
    id: 7,
    name: "Mr. David Brown",
    email: "david.brown@email.com",
    phone: "555-1007",
    occupation: "Accountant",
    address: "321 Elm St, City",
  },
  {
    id: 8,
    name: "Mrs. Emma Brown",
    email: "emma.brown@email.com",
    phone: "555-1008",
    occupation: "Nurse",
    address: "321 Elm St, City",
  },
  {
    id: 9,
    name: "Mr. James Wilson",
    email: "james.wilson@email.com",
    phone: "555-1009",
    occupation: "Manager",
    address: "654 Maple Dr, City",
  },
  {
    id: 10,
    name: "Mrs. Olivia Wilson",
    email: "olivia.wilson@email.com",
    phone: "555-1010",
    occupation: "Designer",
    address: "654 Maple Dr, City",
  },
];

export const studentParentMapping = [
  { studentId: 1, parentId: 1, relation: "Father" },
  { studentId: 1, parentId: 2, relation: "Mother" },
  { studentId: 2, parentId: 3, relation: "Father" },
  { studentId: 2, parentId: 4, relation: "Mother" },
  { studentId: 3, parentId: 5, relation: "Father" },
  { studentId: 3, parentId: 6, relation: "Mother" },
  { studentId: 4, parentId: 7, relation: "Father" },
  { studentId: 4, parentId: 8, relation: "Mother" },
  { studentId: 5, parentId: 9, relation: "Father" },
  { studentId: 5, parentId: 10, relation: "Mother" },
];

export const timetableData = [
  {
    id: 1,
    classId: 21,
    day: "Monday",
    period: 1,
    subjectId: 1,
    teacherId: 1,
    time: "08:00 - 09:00",
  },
  {
    id: 2,
    classId: 21,
    day: "Monday",
    period: 2,
    subjectId: 2,
    teacherId: 2,
    time: "09:00 - 10:00",
  },
  {
    id: 3,
    classId: 21,
    day: "Monday",
    period: 3,
    subjectId: 3,
    teacherId: 4,
    time: "10:00 - 11:00",
  },
  {
    id: 4,
    classId: 21,
    day: "Monday",
    period: 4,
    subjectId: 5,
    teacherId: 3,
    time: "11:00 - 12:00",
  },
  {
    id: 5,
    classId: 21,
    day: "Monday",
    period: 5,
    subjectId: 10,
    teacherId: 10,
    time: "13:00 - 14:00",
  },
  {
    id: 6,
    classId: 21,
    day: "Tuesday",
    period: 1,
    subjectId: 4,
    teacherId: 5,
    time: "08:00 - 09:00",
  },
  {
    id: 7,
    classId: 21,
    day: "Tuesday",
    period: 2,
    subjectId: 1,
    teacherId: 1,
    time: "09:00 - 10:00",
  },
  {
    id: 8,
    classId: 21,
    day: "Tuesday",
    period: 3,
    subjectId: 6,
    teacherId: 6,
    time: "10:00 - 11:00",
  },
  {
    id: 9,
    classId: 21,
    day: "Tuesday",
    period: 4,
    subjectId: 8,
    teacherId: 8,
    time: "11:00 - 12:00",
  },
  {
    id: 10,
    classId: 21,
    day: "Tuesday",
    period: 5,
    subjectId: 11,
    teacherId: 11,
    time: "13:00 - 14:00",
  },
];

// Helper functions to get data
export const getTeacherById = (id) => teachers.find((t) => t.id === id);
export const getSubjectById = (id) => subjects.find((s) => s.id === id);
export const getClassById = (id) => classes.find((c) => c.id === id);
export const getStudentParents = (studentId) => {
  const mappings = studentParentMapping.filter(
    (m) => m.studentId === studentId,
  );
  return mappings.map((m) => ({
    ...parentsData.find((p) => p.id === m.parentId),
    relation: m.relation,
  }));
};

export const getClassTimetable = (classId) => {
  return timetableData
    .filter((t) => t.classId === classId)
    .map((t) => ({
      ...t,
      subject: getSubjectById(t.subjectId),
      teacher: getTeacherById(t.teacherId),
    }));
};

export const getStudentGrades = (studentId) => {
  return gradesData
    .filter((g) => g.studentId === studentId)
    .map((g) => ({
      ...g,
      subject: getSubjectById(g.subjectId),
    }));
};

export const getStudentAttendance = (studentId) => {
  return attendanceData.filter((a) => a.studentId === studentId);
};

export const getClassAttendance = (classId, date) => {
  return attendanceData.filter((a) => a.classId === classId && a.date === date);
};
